import 'dotenv/config';
import { Lobby } from './lobby.class.js';

export const matches = {};
export const lobby = new Lobby();

export const types = {
	ERROR: "ERROR",
	CONNECT_PLAYER: "PLAYER_CONNECTED",
	DISCONNECT_PLAYER: "PLAYER_DISCONNECTED",
	NOT_CONNECTED: "NOT_CONNECTED",
	START_GAME: "START_GAME",
	END_GAME: "END_GAME",
	OPPONENT_CONNECTED: "OPPONENT_CONNECTION",
	OPPONENT_DISCONNECTED: "OPPONENT_CONNECTION",
	MATCH_CREATED: "MATCH_CREATED",
	MATCH_FULL: "MATCH_FULL",
	BALL_BOUNCE: "BALL_BOUNCE",
	LOBBY_ERROR: "LOBBY_ERROR",
	LOBBY_CONNECTED: "LOBBY_CONNECTED",
	TIMEOUT_REMOVE: "TIMEOUT_REMOVE",
	PING: "PING",
	MATCH_REMOVED: "MATCH_REMOVED",
	DUP: "DUPLICATE",
	NOT_FOUND: "NOTFOUND",
};

export const closeCodes = {
	NORMAL: 1000,
	POLICY_VIOLATION: 1008,
	INTERNAL_ERROR: 1011,
}

export const DISCONNECT_TIMEOUT = 60000; // 1 minute
export const INTERVALS = 1000; //1 second
export const FPS = 60;
